[package]
name = "pest_parser_kalyonekenobe"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Grammar parser using 'pest' crate"

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
